# ============================================================================= Quarisma Configuration
# Summary Module
# =============================================================================
# This module provides a function to print a comprehensive summary of the Quarisma build
# configuration, including compiler settings, enabled features, and optional dependencies.
# =============================================================================

# Include guard to prevent multiple inclusions
include_guard(GLOBAL)

# Prints accumulated Quarisma configuration summary
function(print_configuration_summary)
  message("")
  message("******** Summary ********")
  message("General:")
  message("  CMake version         : ${CMAKE_VERSION}")
  message("  CMake command         : ${CMAKE_COMMAND}")
  message("  System                : ${CMAKE_SYSTEM_NAME}")
  message("  C++ compiler          : ${CMAKE_CXX_COMPILER}")
  message("  C++ compiler id       : ${QUARISMA_COMPILER_ID}")
  message("  C++ compiler version  : ${CMAKE_CXX_COMPILER_VERSION}")
  message("  C++ standard          : ${QUARISMA_CXX_STANDARD}")
  message("  Compiler cache        : ${QUARISMA_CACHE_BACKEND}")
  message("  Compiler cache program: ${QUARISMA_CACHE_PROGRAM}")
  message("  CXX flags             : ${CMAKE_CXX_FLAGS}")
  message("  Shared LD flags       : ${CMAKE_SHARED_LINKER_FLAGS}")
  message("  Static LD flags       : ${CMAKE_STATIC_LINKER_FLAGS}")
  message("  Module LD flags       : ${CMAKE_MODULE_LINKER_FLAGS}")
  message("  Build type            : ${CMAKE_BUILD_TYPE}")
  get_directory_property(tmp DIRECTORY ${PROJECT_SOURCE_DIR} COMPILE_DEFINITIONS)
  message("  Compile definitions   : ${tmp}")
  message("  CMAKE_PREFIX_PATH     : ${CMAKE_PREFIX_PATH}")
  message("  CMAKE_INSTALL_PREFIX  : ${CMAKE_INSTALL_PREFIX}")
  message("")
  if(QUARISMA_ENABLE_IWYU)
    message("  IWYU:")
    message("    IWYU executable     : ${QUARISMA_IWYU_EXECUTABLE}")
    message("    IWYU arguments      : ${QUARISMA_IWYU_ARGS}")
  endif()
  get_directory_property(tmp DIRECTORY ${PROJECT_SOURCE_DIR} COMPILE_DEFINITIONS)
  message("  CMake generator       : ${CMAKE_GENERATOR}")
  message("  CMake build tool      : ${CMAKE_BUILD_TOOL}")
  message("  CMake install prefix  : ${CMAKE_INSTALL_PREFIX}")
  message("  CMake build type      : ${CMAKE_BUILD_TYPE}")
  message("  CMake build options   : ${CMAKE_BUILD_OPTIONS}")
  message("  CMake build flags     : ${CMAKE_BUILD_FLAGS}")
  message("  CMAKE_PREFIX_PATH     : ${CMAKE_PREFIX_PATH}")
  message("  CMAKE_INSTALL_PREFIX  : ${CMAKE_INSTALL_PREFIX}")
  message("  QUARISMA_VERSION        : ${QUARISMA_VERSION}")
  message("  BUILD_BINARY          : ${QUARISMA_BINARY_DIR}")
  message("  QUARISMA_DLL_PATHS      : ${QUARISMA_DLL_PATHS}")
  message("  DATA_STORE            : ${QUARISMA_DATA_STORE}")
  message("  QUARISMA_flags:")
  message("    Vectorization       : ${QUARISMA_VECTORIZATION_TYPE}")
  if(QUARISMA_ENABLE_TBB)
    set(_quarisma_parallel_backend "TBB")
  elseif(QUARISMA_ENABLE_OPENMP)
    set(_quarisma_parallel_backend "OpenMP")
  else()
    set(_quarisma_parallel_backend "STDThread")
  endif()
  message("    USE_GOLD_LINKER     : ${QUARISMA_ENABLE_GOLD_LINKER}")
  message("    Multithreading      : ${_quarisma_parallel_backend}")
  message("    Logging backend     : ${QUARISMA_LOGGING_BACKEND}")
  message("    Profiling backend   : ${QUARISMA_PROFILER_TYPE}")
  message("    Cache backend       : ${QUARISMA_CACHE_BACKEND}")
  message("    MKL                 : ${QUARISMA_ENABLE_MKL}")
  message("    Memkind             : ${QUARISMA_ENABLE_MEMKIND}")
  message("    NUMA                : ${QUARISMA_ENABLE_NUMA}")
  message("    Sobol 1111          : ${QUARISMA_SOBOL_1111}")
  message("    LU Pivoting         : ${QUARISMA_LU_PIVOTING}")
  message("    LTO                 : ${QUARISMA_ENABLE_LTO}")
  message("    Magic Enum          : ${QUARISMA_ENABLE_MAGICENUM}")
  message("    Mimalloc            : ${QUARISMA_ENABLE_MIMALLOC}")
  message("    TBB                 : ${QUARISMA_ENABLE_TBB}")
  message("    CUDA                : ${QUARISMA_ENABLE_CUDA}")
  message("    HIP                 : ${QUARISMA_ENABLE_HIP}")
  message("    Enzyme              : ${QUARISMA_ENABLE_ENZYME}")
  message("    Documentation       : ${QUARISMA_BUILD_DOCUMENTATION}")
  message("    External libraries  : ${QUARISMA_ENABLE_EXTERNAL}")

  message("  Build:")
  message("    Shared libs         : ${QUARISMA_BUILD_SHARED_LIBS}")
  if(QUARISMA_WRAP_PYTHON OR QUARISMA_BUILD_WHEEL)
    message("  Python:")
    message("    Build wheel         : ${QUARISMA_BUILD_WHEEL}")
    message("    Python version      : ${QUARISMA_PYTHON_VERSION}")
    message("    Python executable   : ${Python3_EXECUTABLE}")
    message("    Python site-packages: ${QUARISMA_PYTHON_SITE_PACKAGES_SUFFIX}")
  else()
    message("  PYTHON                : OFF")
  endif()
  if(QUARISMA_WRAP_JAVA)
    message("  Java:")
    message("    Java version        : ${Java_VERSION_MAJOR}")
    message("    Java executable     : ${Java_JAR_EXECUTABLE}")
    message("    JNI library         : ${QUARISMA_JNI_LIBRARIES}")
    message("    JNI includes        : ${QUARISMA_JNI_INCLUDE_DIRS}")
  else()
    message("  JAVA                  : OFF")
  endif()
  if(QUARISMA_ENABLE_CUDA)
    message("  CUDA:")
    message("    CUDA include path   : ${CUDA_INCLUDE_DIRS}")
    message("    NVCC executable     : ${CUDA_NVCC_EXECUTABLE}")
    message("    NVCC flags          : ${CMAKE_CUDA_FLAGS}")
    message("    CUDA host compiler  : ${CUDA_HOST_COMPILER}")
    message("    NVCC --device-c     : ${CUDA_SEPARABLE_COMPILATION}")
    message("    CUDA version        : ${CUDA_VERSION}")
    message("    CUDA library        : ${QUARISMA_CUDA_LIBRARIES}")
    message("    CUDA compiler       : ${CMAKE_CUDA_COMPILER}")
    message("    CUDA includes       : ${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES}")
  else()
    message("  CUDA                  : OFF")
  endif()
  if(QUARISMA_BUILD_TESTING)
    message("  Testing:")
    message("    Google test         : ${QUARISMA_ENABLE_GTEST}")
    message("    Benchmark           : ${QUARISMA_ENABLE_BENCHMARK}")
    message("    Valgrind            : ${QUARISMA_ENABLE_VALGRIND}")
    message("    Coverage            : ${QUARISMA_ENABLE_COVERAGE}")
    message("    IWYU                : ${QUARISMA_ENABLE_IWYU}")
    message("    Clang-tidy          : ${QUARISMA_ENABLE_CLANGTIDY}")
    message("    Clang-tidy fix      : ${QUARISMA_ENABLE_FIX}")
    message("    Cppcheck            : ${QUARISMA_ENABLE_CPPCHECK}")
    if(QUARISMA_ENABLE_SANITIZER)
      message("    Sanitizer           : ${QUARISMA_SANITIZER_TYPE}")
    endif()
  endif()

  message("")
endfunction()
